//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodShareApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodHour
    {
        public int FoodHourId { get; set; }
        public int FoodProviderId { get; set; }
        public Nullable<int> OpenHourMo { get; set; }
        public Nullable<int> CloseHourMo { get; set; }
        public Nullable<int> OpenHourTu { get; set; }
        public Nullable<int> CloseHourTu { get; set; }
        public Nullable<int> OpenHourWe { get; set; }
        public Nullable<int> CloseHourWe { get; set; }
        public Nullable<int> OpenHourTh { get; set; }
        public Nullable<int> CloseHourTh { get; set; }
        public Nullable<int> OpenHourFr { get; set; }
        public Nullable<int> CloseHourFr { get; set; }
        public Nullable<int> OpenHourSa { get; set; }
        public Nullable<int> CloseHourSa { get; set; }
        public Nullable<int> OpenHourSu { get; set; }
        public Nullable<int> CloseHourSu { get; set; }
        public string Notes { get; set; }
    }
}
