//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodShareApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public int FoodProviderId { get; set; }
        public int FoodTypeId { get; set; }
        public int FoodAmountId { get; set; }
        public Nullable<bool> Urgent { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
