//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodShareApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodProvider
    {
        public int FoodProviderId { get; set; }
        public string Name { get; set; }
        public string LogoUrl { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Services { get; set; }
        public string Website { get; set; }
        public bool Verified { get; set; }
        public bool Admin { get; set; }
    }
}
