//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodShareApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int TypeId { get; set; }
        public int ToId { get; set; }
        public int FromId { get; set; }
        public string Message { get; set; }
        public bool Viewed { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
